name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy ARM Template (dev)
        uses: azure/cli-action@v1
        with:
          azcliversion: 2.48.1
          inlineScript: |
            az group create --name wus2-ce-dev-rg --location westus2
            az deployment group create --resource-group wus2-ce-dev-rg --template-file arm/azuredeploy.json --parameters @arm/azuredeploy.dev.parameters.json --parameters location=westus2
            echo "::set-output name=app-name::$(az deployment group show -g wus2-ce-dev-rg -n MyAppService --query 'properties.outputs.appName.value' -o tsv)"

      - name: Deploy to Azure Web App (dev)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.deploy_arm_template.outputs.app-name }}
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_dev }}
          package: '.'

  build-and-deploy-prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.9]
    needs: build-and-deploy-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Production approval
        uses: jakejarvis/wait-action@v1.7.0
        with:
          time: '24h'
          message: 'Please approve the deployment'

      - name: Deploy ARM Template (prod)
        uses: azure/cli-action@v1
        with:
          azcliversion: 2.48.1
          inlineScript: |
            az group create --name wus2-ce-prod-rg --location westus2
            az deployment group create --resource-group wus2-ce-prod-rg --template-file arm/azuredeploy.json --parameters @arm/azuredeploy.prod.parameters.json --parameters location=westus2
            echo "::set-output name=app-name::$(az deployment group show -g wus2-ce-prod-rg -n MyAppService --query 'properties.outputs.appName.value' -o tsv)"

      - name: Deploy to Azure Web App