name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.7, 3.8, 3.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy ARM Template (dev)
        uses: azure/CLI@v1
        with:
          azcliversion: 2.2.0
          inlineScript: |
            az deployment group create --resource-group wus2-ce-dev-rg --template-file azuredeploy.json --parameters @azuredeploy.dev.parameters.json --parameters location=westus2
            echo "APP_NAME=$(az deployment group show -g wus2-ce-dev-rg -n MyAppService --query 'properties.outputs.appName.value' -o tsv)" >> $GITHUB_ENV

      - name: Deploy to Azure Web App (dev)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_dev }}
          package: '.'

  build-and-deploy-prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.7, 3.8, 3.9]
    needs: build-and-deploy-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Production approval
        uses: jakejarvis/wait-action@v1.5.0
        with:
          time: '24h'
          message: 'Please approve the deployment'

      - name: Deploy ARM Template (prod)
        uses: azure/CLI@v1
        with:
          azcliversion: 2.2.0
          inlineScript: |
            az deployment group create --resource-group wus2-ce-prod-rg --template-file azuredeploy.json --parameters @azuredeploy.prod.parameters.json --parameters location=westus2
            echo "APP_NAME=$(az deployment group show -g wus2-ce-prod-rg -n MyAppService --query 'properties.outputs.appName.value' -o tsv)" >> $GITHUB_ENV

      - name: Deploy to Azure Web App (prod)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_prod }}
          package: '.'