name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Retrieve APP_NAME output variable
        run: |
          echo "APP_NAME=${{ steps.set_output_var.outputs.APP_NAME }}" >> $GITHUB_ENV

      - name: Deploy ARM Template (dev)
        uses: azure/CLI@v1
        with:
          azcliversion: 2.48.1
          inlineScript: |
            az group create --name wus2-ce-dev-rg --location westus2
            az deployment group create --resource-group wus2-ce-dev-rg --template-file arm/azuredeploy.json --parameters @arm/azuredeploy.dev.parameters.json --parameters location=westus2
            echo "APP_NAME=$(az deployment group show -g wus2-ce-dev-rg -n azuredeploy --query 'properties.outputs.appName.value' -o tsv)" >> $GITHUB_ENV

      - name: Get app name
        id: get_app_name
        run: |
          az deployment group show -g wus2-ce-dev-rg -n azuredeploy --query 'properties.outputs.appName.value' -o tsv > appname.txt
          APP_NAME=$(cat appname.txt | jq -r .)
          echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV

      - name: Deploy to Azure Web App (dev)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_dev }}
          package: '.'

  build-and-deploy-prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.9]
    needs: build-and-deploy-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Retrieve APP_NAME output variable
        run: |
          echo "APP_NAME=${{ steps.set_output_var.outputs.APP_NAME }}" >> $GITHUB_ENV

      - name: Deploy ARM Template (prod)
        uses: azure/CLI@v1
        with:
          azcliversion: 2.48.1
          inlineScript: |
            az group create --name wus2-ce-prd-rg --location westus2
            az deployment group create --resource-group wus2-ce-prod-rg --template-file arm/azuredeploy.json --parameters @arm/azuredeploy.prod.parameters.json --parameters location=westus2
            echo "APP_NAME=$(az deployment group show -g wus2-ce-prod-rg -n azuredeploy --query 'properties.outputs.appName.value' -o tsv)" >> $GITHUB_ENV

      - name: Get app name
        id: get_app_name
        run: |
          az deployment group show -g wus2-ce-prod-rg -n azuredeploy --query 'properties.outputs.appName.value' -o tsv > appname.txt
          APP_NAME=$(cat appname.txt | jq -r .)
          echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV

      - name: Deploy to Azure Web App (prod)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_prod }}
          package: '.'